name: Quarto Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st day of every month

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up Typst
        uses: typst-community/setup-typst@v4
        
      - name: Install required fonts
        run: |
          # Update package list and install required packages
          sudo apt-get update
          sudo apt-get install -y fonts-font-awesome fonts-roboto fonts-liberation
          
          # Download and install Source Sans Pro from a reliable source
          echo "Installing Source Sans Pro..."
          wget -O source-sans-pro.tar.gz https://fonts.gstatic.com/s/sourcesanspro/v22/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7lujVj9w.woff2 || echo "Source Sans Pro download failed"
          
          # Install additional common fonts that might serve as substitutes
          echo "Installing additional font packages..."
          sudo apt-get install -y fonts-dejavu fonts-liberation fonts-noto fonts-open-sans || echo "Additional font installation failed"
          
          # Refresh font cache
          echo "Refreshing font cache..."
          sudo fc-cache -fv
          
          # List all available fonts for debugging
          echo "All available fonts:"
          fc-list | head -20
          
          # Check specifically for fonts that might match our needs
          echo "Checking for font matches..."
          echo "Font Awesome related:"
          fc-list | grep -i "awesome\|fontawesome" || echo "No Font Awesome fonts found"
          echo "Source Sans related:"
          fc-list | grep -i "source" || echo "No Source fonts found"
          echo "Roboto related:"
          fc-list | grep -i "roboto" || echo "No Roboto fonts found"
          echo "Liberation/DejaVu (substitutes):"
          fc-list | grep -i "liberation\|dejavu" | head -5
        
      - name: Compile CV (Typst)
        run: typst compile cv/resume.typ
        
      - name: Commit updated CV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add cv/resume.pdf
          git commit -m "Automated CV update [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
