name: Quarto Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st day of every month

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up Typst
        uses: typst-community/setup-typst@v4
        
      - name: Install required fonts
        run: |
          # Create font directories
          sudo mkdir -p /usr/share/fonts/truetype/fontawesome
          sudo mkdir -p /usr/share/fonts/truetype/source-sans-pro
          sudo mkdir -p /usr/share/fonts/truetype/source-sans-3
          sudo mkdir -p /usr/share/fonts/truetype/roboto
          
          # Install Font Awesome fonts
          echo "Installing Font Awesome fonts..."
          wget -q -O fontawesome.zip https://use.fontawesome.com/releases/v6.4.0/fontawesome-free-6.4.0-desktop.zip
          unzip -q fontawesome.zip
          sudo cp fontawesome-free-6.4.0-desktop/otfs/*.otf /usr/share/fonts/truetype/fontawesome/ || echo "Font Awesome OTF files not found, trying TTF..."
          sudo cp fontawesome-free-6.4.0-desktop/webfonts/*.ttf /usr/share/fonts/truetype/fontawesome/ 2>/dev/null || echo "Font Awesome TTF files not found"
          
          # Install Source Sans Pro
          echo "Installing Source Sans Pro..."
          wget -q -O source-sans-pro.zip "https://fonts.google.com/download?family=Source%20Sans%20Pro"
          unzip -q source-sans-pro.zip -d source-sans-pro
          sudo find source-sans-pro -name "*.ttf" -exec cp {} /usr/share/fonts/truetype/source-sans-pro/ \;
          
          # Install Source Sans 3
          echo "Installing Source Sans 3..."
          wget -q -O source-sans-3.zip "https://fonts.google.com/download?family=Source%20Sans%203"
          unzip -q source-sans-3.zip -d source-sans-3
          sudo find source-sans-3 -name "*.ttf" -exec cp {} /usr/share/fonts/truetype/source-sans-3/ \;
          
          # Install Roboto
          echo "Installing Roboto..."
          wget -q -O roboto.zip "https://fonts.google.com/download?family=Roboto"
          unzip -q roboto.zip -d roboto
          sudo find roboto -name "*.ttf" -exec cp {} /usr/share/fonts/truetype/roboto/ \;
          
          # Clean up
          rm -rf fontawesome* source-sans-pro* source-sans-3* roboto*
          
          # Refresh font cache
          echo "Refreshing font cache..."
          sudo fc-cache -fv
          
          # Verify fonts are installed
          echo "Verifying font installation..."
          fc-list | grep -i "font awesome" || echo "Font Awesome not found in font cache"
          fc-list | grep -i "source sans" || echo "Source Sans not found in font cache"
          fc-list | grep -i "roboto" || echo "Roboto not found in font cache"
        
      - name: Compile CV (Typst)
        run: typst compile cv/resume.typ
        
      - name: Commit updated CV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cv/resume.pdf
          git commit -m "Automated CV update [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
